name: Upload release assets

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Define SDIST_PKG_NAME and BDIST_WHEEL_PKG_NAME
      run: |
        echo "::set-env name=SDIST_PKG_NAME::$(cd dist && ls *.tar.gz)"
        echo "::set-env name=BDIST_WHEEL_PKG_NAME::$(cd dist && ls *.whl)"
    - name: Upload ${{ env.BDIST_WHEEL_PKG_NAME }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/${{ env.BDIST_WHEEL_PKG_NAME }}
        asset_name: ${{ env.BDIST_WHEEL_PKG_NAME }}
        asset_content_type: application/zip
    - name: Upload ${{ env.SDIST_PKG_NAME }}
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/${{ env.SDIST_PKG_NAME }}
        asset_name: ${{ env.SDIST_PKG_NAME }}
        asset_content_type: application/zip
